### ISSUE TITLE
Never ending Github Actions

### ISSUE THREAD

**Issue by pcartas** [Pluralith/pluralith-cli#84]
Hi! im using Pluralith with the CI/CD integration for Github Actions, with my personal account. I dont know if it its a billed feature 
When the job runs this it never finish
```
    - name: Pluralith Init
      uses: Pluralith/actions/init@v1.2.0
      with:
        terraform-path: ${{env.TF_ACTION_WORKING_DIR}}
        api-key: ${{ secrets.PLURALITH_API_KEY }}
        project-id: ${{ secrets.PLURALITH_PROJECT_ID }}
```
![image](https://user-images.githubusercontent.com/82474601/202005401-0032d953-f860-493c-bb0d-ec26aec77d4b.png)
and when i stop the job seems like it was expecting for "Org Id" input

**Comment by DanThePutzer** [comment]
Hi @pcartas thanks for reporting!

We recently released a new version of the CLI that introduced some changes on the init command.

We're currently in the process of updating the GitHub actions to work with the new init command.

Admittedly, we should've updated the Github actions simultaneously, sorry for the disruption!

We'll push a new release for the GitHub actions that fixes the problem tomorrow, I'll report back here once it's available 👍

**Comment by DanThePutzer** [comment]
@pcartas the new actions are out and you should be ready to roll!

**Please make sure to update to v1.3.0** of our actions and check out the docs. There have been a few small changes.
You now need to pass in an org ID and a project ID. There are a few ways to set this up, they are outlined [here in point no. 3](https://github.com/Pluralith/actions#%EF%B8%8F-getting-started).

In your case, if you want to keep passing parameters directly inside the action, the new snipped would look something like this (don't forget to set `PLURALITH_ORG_ID` in your action secret settings):

```yaml
    - name: Pluralith Init
      uses: Pluralith/actions/init@v1.3.0
      with:
        terraform-path: ${{env.TF_ACTION_WORKING_DIR}}
        api-key: ${{ secrets.PLURALITH_API_KEY }}
        org-id: ${{ secrets.PLURALITH_ORG_ID }}
        project-id: ${{ secrets.PLURALITH_PROJECT_ID }}
```

It worked great while testing on my end, but let me know if you run into any issues!
